routes/web.php
        Route::get('/users/getDistrict',['uses' => 'SaleNetworkController@getDistrict','as' =>'users.district']);
        Route::get('/users/getCommune',['uses' => 'SaleNetworkController@getCommune','as' => 'users.coomune']);
        Route::get('/users/cash-export', 'AccountController@download');

        Route::group(['middleware' => ['permission:user-take-cash']], function () {
            Route::resource('/users/account/takecash', 'AccountTakeCashController',['as' => 'users.account']);
        });

        Route::group(['middleware' => ['permission:user-recharge']], function () {
            Route::resource('/users/account/recharge', 'AccountRechargeController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|add-new-user-account|user-account-modification']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log|user-recharge|user-take-cash|add-new-user-account|user-account-modification']], function () {
            Route::get('/users/sale-network/agent-approval',['uses' => 'SaleNetworkController@agentApproval', 'as' => 'users.sale-network.agent-approval']);
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
            Route::resource('/users/direct-user', 'DirectUserController',['as' => 'users']);
        });

        Route::resource('/users/balance-request', 'BalanceRequestController',['as' => 'users']);

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
            

    });

    Route::group(['namespace' => 'Sethei5D'],function(){

        Route::group(['namespace' => 'Order'],function(){
            Route::get('/5d/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => '5d.orders.temp.download']);
            Route::get('/5d/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => '5d.orders.temp.get-order-detail']);
            Route::resource('/5d/orders/temp', 'OrderTempController',['as' => '5d.orders']);
            
            Route::get('/5d/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => '5d.orders.report.download']);
            Route::get('/5d/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => '5d.orders.sum.download']);

            Route::get('/5d/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => '5d.orders.report.get-order-detail']);
            Route::get('/5d/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => '5d.orders.report.selection-form']);
            Route::resource('/5d/orders/report', 'OrderController',['as' => '5d.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/5d/cycles/logs', 'CycleLogController',['as' => '5d.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/5d/game/setting', 'GameController',['as' => '5d.game']);
        });


    });

    Route::group(['namespace' => 'SetheiBall'],function(){
        Route::group(['namespace' => 'Order'],function(){
            Route::get('/ball/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => 'ball.orders.temp.download']);
            Route::get('/ball/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => 'ball.orders.temp.get-order-detail']);
            Route::resource('/ball/orders/temp', 'OrderTempController',['as' => 'ball.orders']);
            
            Route::get('/ball/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => 'ball.orders.report.download']);
            Route::get('/ball/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => 'ball.orders.sum.download']);

            Route::get('/ball/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => 'ball.orders.report.get-order-detail']);
            Route::get('/ball/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => 'ball.orders.report.selection-form']);
            Route::resource('/ball/orders/report', 'OrderController',['as' => 'ball.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/ball/cycles/logs', 'CycleLogController',['as' => 'ball.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/ball/game/setting', 'GameController',['as' => 'ball.game']);
        });

    });

    Route::group(['namespace' => 'Finance'],function(){
        Route::group(['middleware' => ['permission:download-transaction-log']], function () {
            Route::get('/finance/accounts/logs/download', ['uses' => 'AccountLogController@download','as' => 'accounts.logs.download']);
        });
        Route::group(['middleware' => ['permission:view-transaction-log']], function () {
            Route::resource('/finance/accounts/logs', 'AccountLogController',['as' => 'accounts']);    
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/transfer', 'AccountTransferController',['as' => 'accounts']);
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/deposit', 'AccountDepositController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:add-class-manager']], function () {
            Route::resource('/finance/accounts/categories', 'AccountCategoryController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:balance-review']], function () {
            
            Route::get('/finance/accounts/balance/download',['uses' => 'BalanceReviewController@download','as' => 'accounts.balance-review-download']);
            Route::get('/finance/accounts/review-form-selection', ['uses' => 'BalanceReviewController@formSelection', 'as' => 'accounts.review.form-selection']); 
            Route::resource('/finance/accounts/review', 'BalanceReviewController',['as' => 'accounts']); 
           
        });
        Route::group(['middleware' => ['permission:view-platform-account|add-new-account']], function () {
            Route::resource('/finance/accounts', 'AccountController'); 
        });
        Route::group(['middleware' => ['permission:view-agent-tracking|download-agent-tracking']], function () {
            Route::get('/finance/agent-tracking',['uses'=>'AgentTrackingController@index','as'=>'finance.agent-tracking']);
            Route::get('/finance/agent-tracking/download-by-user',['uses'=>'AgentTrackingController@downloadByUser','as'=>'finance.agent-tracking.download-by-user']);
            Route::get('/finance/agent-tracking/download',['uses'=>'AgentTrackingController@investigatedDownload','as'=>'finance.agent-tracking.download']);
        });
        
        Route::group(['middleware' => ['permission:|download-profit-review|download-profit-review']], function () {
            Route::get('/finance/form-selection',['uses'=>'ShopReviewController@formSelection','as'=>'finance.form-selection']);
            Route::get('/finance/profit-view',['uses'=>'ShopReviewController@index','as'=>'finance.profit-view']);
            Route::get('/finance/profit/download',['uses'=>'ShopReviewController@download','as'=>'finance.profit.download']);
        });
    });
   
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);
    Route::get('get-user-account-log-info/{id}',['uses' => 'User\AccountLogController@ajaxGetLogInformation', 'as' => 'user.account.getLogInfo']);

    Route::group(['namespace' => 'Manager'],function(){
        Route::group(['middleware' => ['permission:add-new-role|view-role|role-modification']], function () {
            Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        });
        Route::group(['middleware' => ['permission:view-manager-log']], function () {
            Route::resource('/managers/logs', 'ManagerLogController',['as' => 'managers']);
        });

        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);
        Route::group(['middleware' => ['permission:add-new-manager-account|view-manager-account|manager-account-modification']], function () {
            Route::resource('/managers', 'ManagerController');
        });
    });


    Route::group(['namespace' => 'Promotion'], function(){    
        Route::resource('/promotions', 'PromotionController');
        Route::post('/promotions-saveThumnail', ['uses' => 'PromotionController@saveThumnail', 'as' => 'promotions.saveThumnail' ]);
        Route::delete('/promotions-deleteThumnail', ['uses' => 'PromotionController@deleteThumnail', 'as' => 'promotions.deleteThumnail']);
    });

    // Ajax Routes
    Route::get('get-district-by-province',['uses' => 'SystemSet\Location\DistrictController@getDistrictsByProvinceId', 'as' => 'locations.get-districts-by-province']);
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);

app/Http/Controllers/Api/PromotionController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Promotion;

class PromotionController extends Controller
{
    public function getPromotion(){
        $promotions = Promotion::whereState('1')->get();
        $data = [];
    
        if($promotions->isEmpty()){
            return responseSuccess([
                [
                    'image' => asset("/assets/images/lotto.jpg"),
                ],
                [
                    'image' => asset("/assets/images/5dd.jpg"),
                ]
            ]);
        }    

        

        foreach($promotions as $promotion){
            $image = isset($promotion) ? $promotion->getMedia('images')->first() : null;
            $data [] = [
                'title'=> $promotion['title'],
                'description' => $promotion['description'],
                'begin_date' => $promotion['begin_date'],
                'end_date' => $promotion['end_date'],
                'image' => isset($image)?$image->getFullUrl(): asset("/assets/images/5dd.jpg") 
            ];
        }

        return responseSuccess($data, 'success');
    }
}

app/Http/Controllers/Promotion/PromotionController.php
<?php

namespace App\Http\Controllers\Promotion;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Promotion;
use DB;

class PromotionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $promotions = Promotion::paginate(10);
        return view('promotion.index', compact('promotions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('promotion.add-update');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'file' => 'max:5120',
        ]);

        $this->saveDB($request->all());
        return \redirect(route('promotions.index'))->withSuccess('You just add a new promotion record');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $promotion = Promotion::findOrFail($id);
        return view('promotion.add-update', compact('promotion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'file' => 'max:5120',
        ]);

        $this->saveDB($request->all(), $id);
        return \redirect(route('promotions.index'))->withSuccess("You've just updated a new promotion record");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function saveDB($data, $id = null){
       
        $data['begin_date'] = date("Y-m-d H:i:s",strtotime($data['begin_date']));
        $data['end_date'] = date("Y-m-d H:i:s",strtotime($data['end_date']));
    
        DB::beginTransaction();
        try {
                $promotion = isset($id) ? Promotion::findOrFail($id) : new Promotion;
                $promotion->fill($data);
                $promotion->save();

                if($promotion){
                    if(isset($data['image']) && !empty($data['image'])){
                        $promotion->clearMediaCollection('images');
                        $promotion->addMedia($data['image'])
                             ->toMediaCollection('images');
                        }  
                    }
                DB::commit();        
        } catch (Exception $ex) {
            DB::rollback();
        }
    }


    public function saveThumnail(Request $request){   

        if($request->hasFile('file')){
            $image = $request->file('file');
            $filename = $image->getClientOriginalName();
            $destination = 'asset/admin/images/temp';
    
            $image->move(public_path($destination), $filename);
            $path = $destination.'/'.$filename;
            
           // $path = saveTempImage($request->file('file'));
           // dd($path);
            return response()->json(['Status' => true, 'path' => $path]);
        }
        return response()->json(['Status' => false]);
    }


    public function deleteThumnail(Request $request){
        $result = false;
        $thumnail_id = $request->input('model_id');
        
        DB::beginTransaction();
        try{
            $promotion = Promotion::findOrFail($thumnail_id);
            if($promotion){
                $promotion->clearMediaCollection('images');
                $result = true;
            }

            DB::commit();
        }catch(Exception $exception){
            DB::rollback();
            $result = false;
        }   
        return response()->json(['success' => $result]);
    }
}

resources/views/promotion/add-update.blade.php
@extends('layouts.master')
@section('costom-css')
<style>
    .dropzone .dz-preview .dz-image img{
        width: 100% !important;
    }
    .dropzone .dz-preview .dz-image{
        width: 100% !important;
        height: 100px !important;
    }
</style>
@endsection

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Add Promotion</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route("promotions.index") }}" class="btn btn-primary btn-sm">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{ route('promotions.index') }}" class="breadcrumb-item">Promotion</a>
                <span class="breadcrumb-item active">{{ isset($promotion) ? 'Edit' : 'Add'}}</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($promotion))
        {{ Form::model($promotion,['route' => ['promotions.update',$promotion->id], 'method' => 'PUT']) }}
        @else
        {{ Form::open(['route' => 'promotions.store', 'method' => 'POST']) }}
        @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('title')?'text-danger':'' }}">Promotion Title</label>
                        <div class="position-relative">
                            {{Form::text("title",old("title") ? old("title") : (isset($promotion) ? $promotion->title : ''),
                                ["class" => "form-control ".($errors->has('username')?'border-danger':''),"placeholder" => "Enter account title"])
                            }}
                            @if($errors->has('title'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('title'))
                            <span class="form-text text-danger">{{ $errors->first('title') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('description')?'text-danger':'' }}">Description </label>
                        <div class="position-relative">
                            {{Form::textarea("description",old("description") ? old("description") : (isset($promotion) ? $promotion->description : ''),
                                ["class" => "form-control ".($errors->has('number') ? 'border-danger' : ''),"placeholder" => "Enter description", 'rows' => 3])
                            }}
                            @if($errors->has('description'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('description'))
                            <span class="form-text text-danger">{{ $errors->first('description') }}</span>
                        @endif
                    </div>

                    <div class="row form-group form-group-float form-group-feedback form-group-feedback-right"">
                        
                        <div class="col-md-6 input-group input-group-sm">
                            <div class="input-group-prepend">
                                <div class="input-group-text">{{ $settings['language']['LANG_LABEL_START_DT'] }}</div>
                            </div>
                            <input type="text" class="form-control datetimepicker" value="{{isset($promotion) ? $promotion->begin_date : date('Y-m-d 00:00:00')}}" name="begin_date">
                        </div>

                        <div class="col-md-6 input-group input-group-sm">
                            <div class="input-group-prepend">
                                <div class="input-group-text">{{ $settings['language']['LANG_LABEL_END_DT'] }}</div>
                            </div>
                            <input type="text" class="form-control datetimepicker" value="{{isset($promotion) ? $promotion->end_date : date('Y-m-d 23:59:00')}}" name="end_date">
                        </div>
                    </div>
                    
                    <div class="form-group m-form__group {{ $errors->has('image') ? 'has-danger' : '' }}">
                        <label class="col-form-label" for="image">Thumnail Promotion Image (Ratio 1 : 0.57)</label>
                        <div class="m-dropzone dropzone m-dropzone--primary dz-clickable d-center" action="{{ route('promotions.saveThumnail') }}" data-url-delete="{{ route('promotions.deleteThumnail')}}" id="dropzonePromotionThumnail" data-key="promotionThumnail">
                            @csrf
                            <div class="m-dropzone__msg dz-message needsclick">
                                <h3 class="m-dropzone__msg-title">Drop image here or click to upload.</h3>
                                <span class="m-dropzone__msg-desc">Single Image Upload</span>
                            </div>
                        </div>
                        @if($errors->has('image'))
                            <div id="image-error" class="form-control-feedback">{{ $errors->first('image')}}</div>
                        @endif
                    </div>
                    
                    <div class="form-group mb-3 mb-md-2">
                        <label class="d-block font-weight-semibold">State</label>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="1" class="form-check-input-styled-success" data-fouc {{ isset($promotion) && $promotion->state == 1 ? 'checked' : '' }} checked>
                                Enable
                            </label>
                        </div>
                        <div class="form-check custom-control-inline">
                            <label class="form-check-label">
                                <input type="radio" name="state" value="0" class="form-check-input-styled-danger" data-fouc 
                                    {{ isset($promotion) && $promotion->state == 0 ? 'checked' : '' }}>
                                    Disable
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i>{{ $settings['language']['LANG_BTN_SAVE'] }}
            </button>
        </div>
        
            @php $image = isset($promotion) ? $promotion->getMedia('images')->first() : null; @endphp
            @if(isset($promotion) && $image)
                <input type="hidden" name="image" id="image" value="" data-model-id="{{ $promotion->id }}" data-name="{{$image->file_name}}" data-size="{{$image->size}}" data-url="{{ asset($image->getUrl()) }}">
            @else
                <input type="hidden" name="image" id="image" value="{{old('image')}}">
            @endif
            <input type="hidden" name="action" id="action" value="{{ isset($promotion) ? 'update' : 'add' }}">

        {{ Form::close() }}
    </div>
</div>
@endsection

@section('page-script')
    <script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
    <script src="/global_assets/js/demo_pages/form_checkboxes_radios.js"></script>
    <script src="/global_assets/js/plugins/ui/moment/moment.min.js"></script>
    <script src="/global_assets/js/plugins/pickers/daterangepicker.js"></script>
    <script src="{{ asset('assets/js/dropzone.js')}}"></script>
@endsection

resources/views/promotion/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Promotions</span></h4>
        </div>
        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                @canany(['add-new-account'])
                <a href="{{ route('promotions.create') }}" class="btn btn-link btn-primary btn-sm text-white">
                    <i class="icon-plus-circle2 text-white mr-1"></i> Add Promotion
                </a>
                @endcanany
            </div>
        </div>
    </div>
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Promotions</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    @include('includes.success-msg')
    @include('includes.error-msg')
    
    <div class="card">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr class="bg-slate-800">
                        <th>#</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if($promotions->count() > 0)
                        @foreach($promotions as $key => $row)
                        <tr>
                            <td>{{($promotions->perPage() * ($promotions->currentPage() - 1)) + $key + 1}}</td>
                            <td></td>
                            <td>{{ $row->title }}</td>
                            <td>{{ $row->description }}</td>
                            <td>
                                @if($row->state)
                                    <span class="badge badge-success">Active</span>
                                @else 
                                    <span class="badge badge-danger">Deactive</span>
                                @endif
                            </td>
                            <td>
                                <a href="{{route('promotions.edit',$row->id) }}" class="badge badge-success"><i class="icon-pen6 sm"></i> Edit</a>
                            </td>
                        </tr>
                        @endforeach
                    @else 
                        <tr><td colspan="8">No Data</td></tr>
                    @endif
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            @if($promotions->hasMorePages())
                <div class="mb-2">
                    {!! $promotions->appends(Input::except('page'))->render() !!}
                </div>
            @endif
            <div>
                Showing {{$promotions->firstItem() }} to {{ $promotions->lastItem()}}
                of  {{$promotions->total()}} entries
            </div>
        </div>
    </div>
</div>
@endsection