routes/web.php
<?php
use App\Model\Order;
use App\User;
use App\Model\UserAccount;
use App\Model\UserAccountLog;
use App\Constants\UserAccountConstant;

Route::get('deep',function(){
    return '<a href="intent://open?link_click_id=123456#Intent;scheme=shop;package=com.fighter.sethei_shop;">Click Herre</a>';
});

Route::get('/',function(){
   return redirect()->route('login');
});

Route::group(['namespace' => 'Auth'], function(){
    Route::get('login', ['as' => 'login', 'uses' => 'LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);
});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);
    
    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::group(['namespace' => 'User'],function(){

        Route::get('/users/getDistrict',['uses' => 'SaleNetworkController@getDistrict','as' =>'users.district']);
        Route::get('/users/getCommune',['uses' => 'SaleNetworkController@getCommune','as' => 'users.coomune']);
        Route::get('/users/cash-export', 'AccountController@download');

        Route::group(['middleware' => ['permission:user-take-cash']], function () {
            Route::resource('/users/account/takecash', 'AccountTakeCashController',['as' => 'users.account']);
        });

        Route::group(['middleware' => ['permission:user-recharge']], function () {
            Route::resource('/users/account/recharge', 'AccountRechargeController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|add-new-user-account|user-account-modification']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log|user-recharge|user-take-cash|add-new-user-account|user-account-modification']], function () {
            Route::get('/users/sale-network/agent-approval',['uses' => 'SaleNetworkController@agentApproval', 'as' => 'users.sale-network.agent-approval']);
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
            Route::resource('/users/direct-user', 'DirectUserController',['as' => 'users']);
        });

        Route::resource('/users/balance-request', 'BalanceRequestController',['as' => 'users']);

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
            

    });

    Route::group(['namespace' => 'Sethei5D'],function(){

        Route::group(['namespace' => 'Order'],function(){
            Route::get('/5d/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => '5d.orders.temp.download']);
            Route::get('/5d/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => '5d.orders.temp.get-order-detail']);
            Route::resource('/5d/orders/temp', 'OrderTempController',['as' => '5d.orders']);
            
            Route::get('/5d/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => '5d.orders.report.download']);
            Route::get('/5d/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => '5d.orders.sum.download']);

            Route::get('/5d/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => '5d.orders.report.get-order-detail']);
            Route::get('/5d/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => '5d.orders.report.selection-form']);
            Route::resource('/5d/orders/report', 'OrderController',['as' => '5d.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/5d/cycles/logs', 'CycleLogController',['as' => '5d.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/5d/game/setting', 'GameController',['as' => '5d.game']);
        });


    });

    Route::group(['namespace' => 'SetheiBall'],function(){
        Route::group(['namespace' => 'Order'],function(){
            Route::get('/ball/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => 'ball.orders.temp.download']);
            Route::get('/ball/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => 'ball.orders.temp.get-order-detail']);
            Route::resource('/ball/orders/temp', 'OrderTempController',['as' => 'ball.orders']);
            
            Route::get('/ball/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => 'ball.orders.report.download']);
            Route::get('/ball/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => 'ball.orders.sum.download']);

            Route::get('/ball/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => 'ball.orders.report.get-order-detail']);
            Route::get('/ball/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => 'ball.orders.report.selection-form']);
            Route::resource('/ball/orders/report', 'OrderController',['as' => 'ball.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/ball/cycles/logs', 'CycleLogController',['as' => 'ball.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/ball/game/setting', 'GameController',['as' => 'ball.game']);
        });

    });

    Route::group(['namespace' => 'Finance'],function(){
        Route::group(['middleware' => ['permission:download-transaction-log']], function () {
            Route::get('/finance/accounts/logs/download', ['uses' => 'AccountLogController@download','as' => 'accounts.logs.download']);
        });
        Route::group(['middleware' => ['permission:view-transaction-log']], function () {
            Route::resource('/finance/accounts/logs', 'AccountLogController',['as' => 'accounts']);    
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/transfer', 'AccountTransferController',['as' => 'accounts']);
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/deposit', 'AccountDepositController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:add-class-manager']], function () {
            Route::resource('/finance/accounts/categories', 'AccountCategoryController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:balance-review']], function () {
            
            Route::get('/finance/accounts/balance/download',['uses' => 'BalanceReviewController@download','as' => 'accounts.balance-review-download']);
            Route::get('/finance/accounts/review-form-selection', ['uses' => 'BalanceReviewController@formSelection', 'as' => 'accounts.review.form-selection']); 
            Route::resource('/finance/accounts/review', 'BalanceReviewController',['as' => 'accounts']); 
           
        });
        Route::group(['middleware' => ['permission:view-platform-account|add-new-account']], function () {
            Route::resource('/finance/accounts', 'AccountController'); 
        });
        Route::group(['middleware' => ['permission:view-agent-tracking|download-agent-tracking']], function () {
            Route::get('/finance/agent-tracking',['uses'=>'AgentTrackingController@index','as'=>'finance.agent-tracking']);
            Route::get('/finance/agent-tracking/download-by-user',['uses'=>'AgentTrackingController@downloadByUser','as'=>'finance.agent-tracking.download-by-user']);
            Route::get('/finance/agent-tracking/download',['uses'=>'AgentTrackingController@investigatedDownload','as'=>'finance.agent-tracking.download']);
        });
        
        Route::group(['middleware' => ['permission:|download-profit-review|download-profit-review']], function () {
            Route::get('/finance/form-selection',['uses'=>'ShopReviewController@formSelection','as'=>'finance.form-selection']);
            Route::get('/finance/profit-view',['uses'=>'ShopReviewController@index','as'=>'finance.profit-view']);
            Route::get('/finance/profit/download',['uses'=>'ShopReviewController@download','as'=>'finance.profit.download']);
        });
    });
   
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);
    Route::get('get-user-account-log-info/{id}',['uses' => 'User\AccountLogController@ajaxGetLogInformation', 'as' => 'user.account.getLogInfo']);

    Route::group(['namespace' => 'Manager'],function(){
        Route::group(['middleware' => ['permission:add-new-role|view-role|role-modification']], function () {
            Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        });
        Route::group(['middleware' => ['permission:view-manager-log']], function () {
            Route::resource('/managers/logs', 'ManagerLogController',['as' => 'managers']);
        });

        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);

app/Http/Controllers/Api/AccountController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Validator;

class AccountController extends Controller
{
    
}

app/Http/Controllers/Finance/AccountController.php
<?php

namespace App\Http\Controllers\Finance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\SystemAccountType;
use App\Model\SystemAccount;
use App\Model\SystemAccountCategory;
use DB;

class AccountController extends Controller
{
    
    public function index()
    {
    
      //  $accounts = SystemAccount::with('type','category')->where('state',1)->OrderBy('sort','ASC')->paginate(15);
        $accounts = SystemAccount::where('state',1)->OrderBy('sort','ASC')->paginate(15);
        return view("finance.account.index",compact('accounts'));
    }

    public function create()
    {
        // $types = SystemAccountType::all()->pluck('name','id');
        // $categories = SystemAccountCategory::all()->pluck('name','id');
       
        return view("Finance.account.add-update",compact('types','categories'));
    }

  
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'title' => 'required|unique:system_accounts,title',
            'number' => 'required'
        ]);

        $this->saveDB($request->all());
        return redirect()->route('accounts.index')->withSucess('You have just Added an Account Successful');
    }

  
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        $account = SystemAccount::findOrFail($id);
        // $types = SystemAccountType::all()->pluck('name','id');
        // $categories = SystemAccountCategory::all()->pluck('name','id');
        return view("finance.account.add-update",compact('account','types','categories'));
    }

   
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required',
            'title' => 'required|unique:system_accounts,title,'.$id,
            'number' => 'required'
        ]);
        
        $this->saveDB($request->all(),$id);
        return redirect()->route('accounts.index')->withSucess('You have just Added an Account Successful');
    }

  
    public function destroy($id)
    {
        //
    }

    public function saveDB($data , $id=null){
       
        $account = null;
        DB::beginTransaction();
        try{
            $account = isset($id) ? SystemAccount::find($id) : new SystemAccount();
            if(!$account) return redirect()->back()->withError('There is no record found!');
            $account->fill($data);
            $account->save($data);
            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError("There error with during operation");
        }
        return $account;
    }
}

resources/views/finance/account/category/add-update.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Add Account Class</span></h4>
        </div>

        <div class="header-elements d-none">
            @canany('view-platform-account')
                <div class="d-flex justify-content-center">
                    <a href="{{ route('accounts.categories.index') }}" class="btn btn-primary btn-sm">
                        <i class="icon-square-left mr-1"></i> Back
                    </a>
                </div>
            @endcanany
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{route('accounts.index')}}" class="breadcrumb-item">{{ $settings['language']['LANG_MENU_FINANCE'] }}</a>
                <a href="{{route('accounts.index')}}" class="breadcrumb-item">{{ $settings['language']['LANG_MENU_ACCOUNT'] }}</a>
                <a href="{{route('accounts.categories.index')}}" class="breadcrumb-item">Class Manager</a>
                <span class="breadcrumb-item active">{{ isset($category) ? 'Edit' : 'Add'}}</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($category))
        {{ Form::model($category,['route' => ['accounts.categories.update',$category->id], 'method' => 'PUT']) }}
        @else
        {{ Form::open(['route' => 'accounts.categories.store', 'method' => 'POST']) }}
        @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group select2">
                        <label>Account Type</label>
                        {{Form::select("type_id",$types, isset($category) && $category->type_id ? $category->type->id : null,["class" => "form-control"])}}
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('name')?'text-danger':'' }}">{{ $settings['language']['LANG_LABEL_ACCOUNT_NAME'] }} </label>
                        <div class="position-relative">
                            {{Form::text("name",old("name") ? old("name") : (isset($category) ? $category->name : ''),
                                ["class" => "form-control ".($errors->has('name')?'border-danger':''),"placeholder" => "Enter account name"])
                            }}
                            @if($errors->has('name'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('name'))
                            <span class="form-text text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">Sort (0 ~ 99)</label>
                        <div class="position-relative">
                            {{Form::number("sort",old("sort") ? old("sort") : (isset($category) ? $category->sort : '0'),
                                ["class" => "form-control", "min" => 0])
                            }}
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> {{ $settings['language']['LANG_BTN_SAVE']  }}
            </button>
        </div>
        {{ Form::close() }}
    </div>
</div>
@endsection

@section('page-script')
<script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>}
<script src="/global_assets/js/demo_pages/form_checkboxes_radios.js"></script>
@endsection

resources/views/finance/account/category/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Account Class Manager</span></h4>
        </div>
        <div class="header-elements d-none">
            {{-- @canany('view-platform-account') --}}
                <div class="d-flex justify-content-center">
                    <a href="{{ route('accounts.categories.create') }}" class="btn btn-link btn-primary btn-sm text-white">
                        <i class="icon-plus-circle2 text-white mr-1"></i> Add Class
                    </a>
                </div>
            {{-- @endcanany --}}
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{ route('accounts.index') }}" class="breadcrumb-item">{{ $settings['language']['LANG_MENU_FINANCE'] }}</a>
                <span class="breadcrumb-item active">{{ $settings['language']['LANG_MENU_ACCOUNT'] }}</span>
                <span class="breadcrumb-item active">Class Manager</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    @include('includes.success-msg')
    @include('includes.error-msg')
    <div class="card">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr class="bg-slate-800">
                        <th>#</th>
                        <th>{{ $settings['language']['LANG_LABEL_ACCOUNT_TYPE'] }}</th>
                        <th>{{ $settings['language']['LANG_LABEL_CLASS_NAME'] }}</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if($categories->count() > 0)
                        @foreach($categories as $key => $row)
                        <tr>
                            <td>{{($categories->perPage() * ($categories->currentPage() - 1)) + $key + 1}}</td>
                            <td>{{ $row->type ? $row->type->name : '' }}</td>
                            <td>{{ $row->name }}</td>
                            @canany('view-platform-account')
                            <td class="group-btn-action">
                                <a href="{{ route('accounts.categories.edit',$row->id) }}" class="btn btn-sm btn-outline bg-teal-400 text-teal-400 border-teal-400 btn-icon border-2" data-popup="tooltip" title="" data-placement="bottom" data-original-title="Edit"><i class="icon-pencil7"></i> Edit</a>
                            </td>
                            @endcanany
                            {{-- <td class="group-btn-action">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline bg-teal-400 text-teal-400 border-teal-400 border-2 dropdown-toggle mr-1" data-toggle="dropdown" aria-expanded="false"><i class="icon-cog5"></i> Action</button>
                                    <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(135px, 36px, 0px);">
                                        <a href="{{route('accounts.categories.edit',$row->id)}}" class="dropdown-item"><i class="icon-pen6"></i> Edit</a>
                                    </div>
                                </div>
                            </td> --}}
                        </tr>
                        @endforeach
                    @else 
                        <tr><td colspan="3">No Data</td></tr>
                    @endif
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            @if($categories->hasMorePages())
                <div class="mb-2">
                    {!! $categories->appends(Input::except('page'))->render() !!}
                </div>
            @endif
            <div>
                Showing {{$categories->firstItem()}} to {{$categories->lastItem()}}
                of  {{$categories->total()}} entries
            </div>
        </div>
    </div>
</div>
@endsection