routes/web.php
<?php
use App\Model\Order;
use App\User;
use App\Model\UserAccount;
use App\Model\UserAccountLog;
use App\Constants\UserAccountConstant;

Route::get('deep',function(){
    return '<a href="intent://open?link_click_id=123456#Intent;scheme=shop;package=com.fighter.sethei_shop;">Click Herre</a>';
});

Route::get('/',function(){
   return redirect()->route('login');
});

Route::group(['namespace' => 'Auth'], function(){
    Route::get('login', ['as' => 'login', 'uses' => 'LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);
});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);
    
    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::group(['namespace' => 'User'],function(){

        Route::get('/users/getDistrict',['uses' => 'SaleNetworkController@getDistrict','as' =>'users.district']);
        Route::get('/users/getCommune',['uses' => 'SaleNetworkController@getCommune','as' => 'users.coomune']);
        Route::get('/users/cash-export', 'AccountController@download');

        Route::group(['middleware' => ['permission:user-take-cash']], function () {
            Route::resource('/users/account/takecash', 'AccountTakeCashController',['as' => 'users.account']);
        });

        Route::group(['middleware' => ['permission:user-recharge']], function () {
            Route::resource('/users/account/recharge', 'AccountRechargeController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|add-new-user-account|user-account-modification']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log|user-recharge|user-take-cash|add-new-user-account|user-account-modification']], function () {
            Route::get('/users/sale-network/agent-approval',['uses' => 'SaleNetworkController@agentApproval', 'as' => 'users.sale-network.agent-approval']);
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
            Route::resource('/users/direct-user', 'DirectUserController',['as' => 'users']);
        });

        Route::resource('/users/balance-request', 'BalanceRequestController',['as' => 'users']);

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
            

    });

    Route::group(['namespace' => 'Sethei5D'],function(){

        Route::group(['namespace' => 'Order'],function(){
            Route::get('/5d/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => '5d.orders.temp.download']);
            Route::get('/5d/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => '5d.orders.temp.get-order-detail']);
            Route::resource('/5d/orders/temp', 'OrderTempController',['as' => '5d.orders']);
            
            Route::get('/5d/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => '5d.orders.report.download']);
            Route::get('/5d/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => '5d.orders.sum.download']);

            Route::get('/5d/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => '5d.orders.report.get-order-detail']);
            Route::get('/5d/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => '5d.orders.report.selection-form']);
            Route::resource('/5d/orders/report', 'OrderController',['as' => '5d.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/5d/cycles/logs', 'CycleLogController',['as' => '5d.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/5d/game/setting', 'GameController',['as' => '5d.game']);
        });


    });

    Route::group(['namespace' => 'SetheiBall'],function(){
        Route::group(['namespace' => 'Order'],function(){
            Route::get('/ball/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => 'ball.orders.temp.download']);
            Route::get('/ball/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => 'ball.orders.temp.get-order-detail']);
            Route::resource('/ball/orders/temp', 'OrderTempController',['as' => 'ball.orders']);
            
            Route::get('/ball/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => 'ball.orders.report.download']);
            Route::get('/ball/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => 'ball.orders.sum.download']);

            Route::get('/ball/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => 'ball.orders.report.get-order-detail']);
            Route::get('/ball/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => 'ball.orders.report.selection-form']);
            Route::resource('/ball/orders/report', 'OrderController',['as' => 'ball.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/ball/cycles/logs', 'CycleLogController',['as' => 'ball.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/ball/game/setting', 'GameController',['as' => 'ball.game']);
        });

    });

    Route::group(['namespace' => 'Finance'],function(){
        Route::group(['middleware' => ['permission:download-transaction-log']], function () {
            Route::get('/finance/accounts/logs/download', ['uses' => 'AccountLogController@download','as' => 'accounts.logs.download']);
        });
        Route::group(['middleware' => ['permission:view-transaction-log']], function () {
            Route::resource('/finance/accounts/logs', 'AccountLogController',['as' => 'accounts']);    
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/transfer', 'AccountTransferController',['as' => 'accounts']);
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/deposit', 'AccountDepositController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:add-class-manager']], function () {
            Route::resource('/finance/accounts/categories', 'AccountCategoryController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:balance-review']], function () {
            
            Route::get('/finance/accounts/balance/download',['uses' => 'BalanceReviewController@download','as' => 'accounts.balance-review-download']);
            Route::get('/finance/accounts/review-form-selection', ['uses' => 'BalanceReviewController@formSelection', 'as' => 'accounts.review.form-selection']); 
            Route::resource('/finance/accounts/review', 'BalanceReviewController',['as' => 'accounts']); 
           
        });
        Route::group(['middleware' => ['permission:view-platform-account|add-new-account']], function () {
            Route::resource('/finance/accounts', 'AccountController'); 
        });
        Route::group(['middleware' => ['permission:view-agent-tracking|download-agent-tracking']], function () {
            Route::get('/finance/agent-tracking',['uses'=>'AgentTrackingController@index','as'=>'finance.agent-tracking']);
            Route::get('/finance/agent-tracking/download-by-user',['uses'=>'AgentTrackingController@downloadByUser','as'=>'finance.agent-tracking.download-by-user']);
            Route::get('/finance/agent-tracking/download',['uses'=>'AgentTrackingController@investigatedDownload','as'=>'finance.agent-tracking.download']);
        });
        
        Route::group(['middleware' => ['permission:|download-profit-review|download-profit-review']], function () {
            Route::get('/finance/form-selection',['uses'=>'ShopReviewController@formSelection','as'=>'finance.form-selection']);
            Route::get('/finance/profit-view',['uses'=>'ShopReviewController@index','as'=>'finance.profit-view']);
            Route::get('/finance/profit/download',['uses'=>'ShopReviewController@download','as'=>'finance.profit.download']);
        });
    });
   
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);
    Route::get('get-user-account-log-info/{id}',['uses' => 'User\AccountLogController@ajaxGetLogInformation', 'as' => 'user.account.getLogInfo']);

    Route::group(['namespace' => 'Manager'],function(){
        Route::group(['middleware' => ['permission:add-new-role|view-role|role-modification']], function () {
            Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        });
        Route::group(['middleware' => ['permission:view-manager-log']], function () {
            Route::resource('/managers/logs', 'ManagerLogController',['as' => 'managers']);
        });

        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class UserController extends Controller
{
    public function getProfile(){

        $user = auth()->user();

        $data = [
            'username' => $user->username,
            'account_number' => $user->account_number,
            'phone' => $user->phone,
            'email' => $user->email,
            'national_id_number' => $user->national_id_number,
            'image' => ''
            // 'main_balance' => $user->cashAccount->balance,
            // 'bonus_5d' => $user->bonus5dAccount->balance,
            // 'bonus_ball' => $user->bonusBallAccount->balance,
        ];

        return responseSuccess($data, 'success');
    }

    public function get_user_by_account_number(){

        $list = [];
        $user = User::whereAccountNumber(request()->account_number)->first();

        if(!$user){
            return responseError('User Account Not Found');
        }

        $parent = User::find($user->id);
        $child = $parent ? $parent->children()->get() : [];

        $data = [
            'userId' => $parent->id,
            'username' => $parent->username,
            'account_number' => $parent->account_number,
            'phone' => $parent->phone,
            'image' => ''
        ];
        
        foreach($child as $children){
            $list [] = [
                'userId' => $children->id,
                'username' => $children->username,
                'account_number' => $children->account_number,
                'phone' => $children->phone,
                'image' => ''
            ];
        }
       
        return responseSuccess([ 'parent' => $data , 'children' => $list ]);
    }
}

app/Http/Controllers/User/AccountController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Model\Account;
use App\Model\UserAccount;
use DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Response;

class AccountController extends Controller
{
    public function show($id)
    {
        DB::beginTransaction();
        try{
            $user = User::with('userAccounts')->whereId($id)->first();
            if(!$user)
                return redirect()->back()->withInput()->withError('Unknown User!');
            $accounts = $user->userAccounts;
            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withInput()->withError('There was an error during operation!');
        }
        return view('user.account.index',compact('user','accounts'));
    }

    public function download(){

        ini_set('max_execution_time', 3600);
        ini_set('memory_limit', '-1');
        
        
        $users = User::with('cashAccount','ballCashAccount')
                        ->whereState(1)
                        ->whereIsTest(0)
                        ->whereIn('level',[0,2,3,4,5,6,7,8])
                        ->get(); 
        
        
        $path = $this->writeExcel($users);
        return response()->download($path);
        // return Response::download($path);
        // return response()->json(['path' => $path, 'success' => true]);
    }

    public function writeExcel($data){
        $spreadsheet = new Spreadsheet();
        $spreadsheet->setActiveSheetIndex(0);
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('List of Users');
        $spreadsheet = $this->writeDetailWorksheet($spreadsheet, $sheet, $data);
        
        $writer = new Xlsx($spreadsheet);
        if(!is_dir(public_path('backup'))) mkdir(public_path('backup'),0777,true);
        $writer->save(public_path('backup').'/'.'List-of-Users.xlsx');
        $path = asset('backup/List-of-Users.xlsx');
        return $path;
    }

    public function writeDetailWorksheet($spreadsheet, $sheet, $data){
        $columnNames = ['Account ID', 'Account Name','User Type','Province','5D Balance','Ball Balance'];
        $sheet = $this->writeHeaderWorksheet($sheet, $columnNames);
        
        $i = 2;
        foreach( $data as $l => $user){
            $sheet->setCellValueExplicit('A'.$i, $user->account_number, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);
            $sheet->setCellValue('B'.$i, $user->username);
            $sheet->setCellValue('C'.$i, $this->getUserType($user->level));
            $sheet->setCellValue('D'.$i, $user->province);
            $sheet->setCellValue('E'.$i, $user->cashAccount ? $user->cashAccount->balance : 0);
            $sheet->setCellValue('F'.$i, $user->ballCashAccount ? $user->ballCashAccount->balance : 0);
          
            $i++;
        }
        
        return $spreadsheet;
    }

    public function writeHeaderWorksheet($sheet, $columnNames){
        $columns = [];
        $a = 'A';
        foreach($columnNames as $index => $value){
            array_push($columns, $a++);
        }

        for($iterator=0;$iterator<count($columns);$iterator++){
            $sheet->setCellValue($columns[$iterator].'1', $columnNames[$iterator]);
            $sheet->getStyle($columns[$iterator].'1')
                ->getFill()
                ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
                ->getStartColor()
                ->setARGB('888888');

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->getColor()
                ->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->setSize(11);

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->setBold(true);
            $sheet->getColumnDimension($columns[$iterator])->setAutoSize(true);
        }

        return $sheet;
    }

    public function getUserType($lv){
        $type = "";

        switch ($lv) {
            case 8:
                $type = "Agent";
                break;
            
            case 7:
                $type = "Master Agent";
                break;

            case 6:
                $type = "Network Sale";
                break;
            
            case 5:
                $type = "Network Team Leader";
                break;

            case 4:
                $type = "Network Master";
                break;

            case 3:
                $type = "District Sale";
                break;

            case 2:
                $type = "Provincial Manager";
                break;

            case 0:
                $type = "Direct User";
                break;

            default:
                $type = "";
                break;
        }

        return $type;
    }
}

app/Http/Controllers/User/DirectUserController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Illuminate\Pagination\LengthAwarePaginator;
use App\User;
use App\Constants\Account;

class DirectUserController extends Controller
{
    public function index()
    {   
        $state = request()->get('state') ?? 'all';
        $keyword = request()->get('keyword') ?? '';
        
        $users = User::with('cashAccount','children')->where(['com_direct' => 1]);
        $users = $users->when($state != 'all',function($q) use ($state){
                        return $q->where(['state' => $state]);
                    })->when($keyword != '',function($q) use ($keyword){
                        return $q->where('username','LIKE','%'.$keyword.'%')
                                 ->orWhere('account_number','LIKE','%'.$keyword.'%');
                    })->orderBy('id','DESC')->paginate(20);
        
        return view('user.direct-user.index',compact('users'));
    }
}

resources/views/user/takecash/add-update.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">User Account Withdraw – {{ $user->username }}</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ URL::previous() }}" class="btn btn-primary btn-sm">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{ route('users.sale-network.index') }}" class="breadcrumb-item">{{ $settings['language']['LANG_MENU_USER_LIST'] }}</a>
                <a href="{{ route('users.sale-network.index') }}" class="breadcrumb-item">{{ $settings['language']['LANG_MENU_SALE_NET'] }}</a>
                <span class="breadcrumb-item active">User Withdraw</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        {{ Form::open(['route' => ['users.account.takecash.update',$user->id], 'method' => 'PUT','autocomplete' => "off"]) }}
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    @include('includes.success-msg')
                    @include('includes.error-msg')
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">{{ $settings['language']['LANG_LABEL_ACCOUNT'] }}</label>
                        <div class="position-relative">
                            {{Form::select("account",$accounts, null, ["class" => "form-control input-sm"])}}
                        </div>
                        @if($errors->has('account'))
                            <span class="form-text text-danger">{{ $errors->first('account') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">{{ $settings['language']['LANG_LABEL_USERNAME'] }}</label>
                        <div class="position-relative">
                            {{Form::text("username", $user->username,
                                ["class" => "form-control", 'disabled'])
                            }}
                        </div>
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">{{ $settings['language']['LANG_LABEL_BALANCE'] }} (R)</label>
                        <div class="position-relative">
                            {{Form::text("balance",isset($user) && $user->cashAccount ? currencyFormat($user->cashAccount->balance) : 0,
                                ["class" => "form-control", 'disabled'])
                            }}
                        </div>
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('amount')?'text-danger':'' }}">{{ $settings['language']['LANG_LABEL_AMOUNT'] }} (R)</label>
                        <div class="position-relative">
                            {{Form::text("amount",number_format(request()->get('amount',0),0),
                                ["class" => "form-control input-amount ".($errors->has('amount')?'border-danger':''), "min" => 0, 'maxlength' => 32])
                            }}
                            @if($errors->has('amount'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('amount'))
                            <span class="form-text text-danger">{{ $errors->first('amount') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('user_pay_password')?'text-danger':'' }}">User Pay Password</label>
                        <div class="position-relative">
                            {{Form::password("user_pay_password",
                                ["class" => "form-control ".($errors->has('user_pay_password')?'border-danger':''),"placeholder" => "Enter pay password"])
                            }}
                            @if($errors->has('user_pay_password'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('user_pay_password'))
                            <span class="form-text text-danger">{{ $errors->first('user_pay_password') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('pay_password')?'text-danger':'' }}">{{ $settings['language']['LANG_LABEL_PAYPASS'] }}</label>
                        <div class="position-relative">
                            {{Form::password("pay_password",
                                ["class" => "form-control ".($errors->has('pay_password')?'border-danger':''),"placeholder" => "Enter pay password"])
                            }}
                            @if($errors->has('pay_password'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('pay_password'))
                            <span class="form-text text-danger">{{ $errors->first('pay_password') }}</span>
                        @endif
                    </div>
                </div>

                @php $image = $user->getFirstMedia('id_card'); @endphp
                @if($image)
                <div class="col-lg-6">
                    <img src="{{$image->getUrl()}}" class="w-100" alt="">
                </div>
                @endif
            </div>
            
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> {{ $settings['language']['LANG_BTN_SAVE'] }}
            </button>
        </div>
        <input type="hidden" name="br" value="{{ request()->get('br','') }}">
        {{ Form::close() }}
    </div>
</div>
@endsection