routes/web.php
<?php
use App\Model\Order;
use App\User;
use App\Model\UserAccount;
use App\Model\UserAccountLog;
use App\Constants\UserAccountConstant;

Route::get('deep',function(){
    return '<a href="intent://open?link_click_id=123456#Intent;scheme=shop;package=com.fighter.sethei_shop;">Click Herre</a>';
});

Route::get('/',function(){
   return redirect()->route('login');
});

Route::group(['namespace' => 'Auth'], function(){
    Route::get('login', ['as' => 'login', 'uses' => 'LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);
});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);
    
    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::group(['namespace' => 'User'],function(){

        Route::get('/users/getDistrict',['uses' => 'SaleNetworkController@getDistrict','as' =>'users.district']);
        Route::get('/users/getCommune',['uses' => 'SaleNetworkController@getCommune','as' => 'users.coomune']);
        Route::get('/users/cash-export', 'AccountController@download');

        Route::group(['middleware' => ['permission:user-take-cash']], function () {
            Route::resource('/users/account/takecash', 'AccountTakeCashController',['as' => 'users.account']);
        });

        Route::group(['middleware' => ['permission:user-recharge']], function () {
            Route::resource('/users/account/recharge', 'AccountRechargeController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|add-new-user-account|user-account-modification']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log|user-recharge|user-take-cash|add-new-user-account|user-account-modification']], function () {
            Route::get('/users/sale-network/agent-approval',['uses' => 'SaleNetworkController@agentApproval', 'as' => 'users.sale-network.agent-approval']);
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
            Route::resource('/users/direct-user', 'DirectUserController',['as' => 'users']);
        });

        Route::resource('/users/balance-request', 'BalanceRequestController',['as' => 'users']);

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
            

    });

    Route::group(['namespace' => 'Sethei5D'],function(){

        Route::group(['namespace' => 'Order'],function(){
            Route::get('/5d/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => '5d.orders.temp.download']);
            Route::get('/5d/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => '5d.orders.temp.get-order-detail']);
            Route::resource('/5d/orders/temp', 'OrderTempController',['as' => '5d.orders']);
            
            Route::get('/5d/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => '5d.orders.report.download']);
            Route::get('/5d/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => '5d.orders.sum.download']);

            Route::get('/5d/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => '5d.orders.report.get-order-detail']);
            Route::get('/5d/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => '5d.orders.report.selection-form']);
            Route::resource('/5d/orders/report', 'OrderController',['as' => '5d.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/5d/cycles/logs', 'CycleLogController',['as' => '5d.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/5d/game/setting', 'GameController',['as' => '5d.game']);
        });


    });

    Route::group(['namespace' => 'SetheiBall'],function(){
        Route::group(['namespace' => 'Order'],function(){
            Route::get('/ball/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => 'ball.orders.temp.download']);
            Route::get('/ball/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => 'ball.orders.temp.get-order-detail']);
            Route::resource('/ball/orders/temp', 'OrderTempController',['as' => 'ball.orders']);
            
            Route::get('/ball/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => 'ball.orders.report.download']);
            Route::get('/ball/orders/sum/agent',['uses' => 'OrderController@downloadSumBet','as' => 'ball.orders.sum.download']);

            Route::get('/ball/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => 'ball.orders.report.get-order-detail']);
            Route::get('/ball/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => 'ball.orders.report.selection-form']);
            Route::resource('/ball/orders/report', 'OrderController',['as' => 'ball.orders']);
        });

        Route::group(['namespace' => 'Cycle'],function(){
            Route::resource('/ball/cycles/logs', 'CycleLogController',['as' => 'ball.cycles']);
        });

        Route::group(['namespace' => 'Game'],function(){
            Route::resource('/ball/game/setting', 'GameController',['as' => 'ball.game']);
        });

    });

    Route::group(['namespace' => 'Finance'],function(){
        Route::group(['middleware' => ['permission:download-transaction-log']], function () {
            Route::get('/finance/accounts/logs/download', ['uses' => 'AccountLogController@download','as' => 'accounts.logs.download']);
        });
        Route::group(['middleware' => ['permission:view-transaction-log']], function () {
            Route::resource('/finance/accounts/logs', 'AccountLogController',['as' => 'accounts']);    
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/transfer', 'AccountTransferController',['as' => 'accounts']);
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/deposit', 'AccountDepositController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:add-class-manager']], function () {
            Route::resource('/finance/accounts/categories', 'AccountCategoryController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:balance-review']], function () {
            
            Route::get('/finance/accounts/balance/download',['uses' => 'BalanceReviewController@download','as' => 'accounts.balance-review-download']);
            Route::get('/finance/accounts/review-form-selection', ['uses' => 'BalanceReviewController@formSelection', 'as' => 'accounts.review.form-selection']); 
            Route::resource('/finance/accounts/review', 'BalanceReviewController',['as' => 'accounts']); 
           
        });
        Route::group(['middleware' => ['permission:view-platform-account|add-new-account']], function () {
            Route::resource('/finance/accounts', 'AccountController'); 
        });
        Route::group(['middleware' => ['permission:view-agent-tracking|download-agent-tracking']], function () {
            Route::get('/finance/agent-tracking',['uses'=>'AgentTrackingController@index','as'=>'finance.agent-tracking']);
            Route::get('/finance/agent-tracking/download-by-user',['uses'=>'AgentTrackingController@downloadByUser','as'=>'finance.agent-tracking.download-by-user']);
            Route::get('/finance/agent-tracking/download',['uses'=>'AgentTrackingController@investigatedDownload','as'=>'finance.agent-tracking.download']);
        });
        
        Route::group(['middleware' => ['permission:|download-profit-review|download-profit-review']], function () {
            Route::get('/finance/form-selection',['uses'=>'ShopReviewController@formSelection','as'=>'finance.form-selection']);
            Route::get('/finance/profit-view',['uses'=>'ShopReviewController@index','as'=>'finance.profit-view']);
            Route::get('/finance/profit/download',['uses'=>'ShopReviewController@download','as'=>'finance.profit.download']);
        });
    });
   
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);
    Route::get('get-user-account-log-info/{id}',['uses' => 'User\AccountLogController@ajaxGetLogInformation', 'as' => 'user.account.getLogInfo']);

    Route::group(['namespace' => 'Manager'],function(){
        Route::group(['middleware' => ['permission:add-new-role|view-role|role-modification']], function () {
            Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        });
        Route::group(['middleware' => ['permission:view-manager-log']], function () {
            Route::resource('/managers/logs', 'ManagerLogController',['as' => 'managers']);
        });

        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use Request;
use App\Http\Controllers\Controller;
use App\Http\Services\OrderService;
use Exception;
use DB;

class OrderController extends Controller
{
    function order(){
    
        $this->validate(request(),[
            'bet_body' => 'required'
        ]); 

        $bet_body = request()->get('bet_body');
        $device_name = request()->get('device_name');
        $device_uuid = request()->get('device_uuid');

        DB::beginTransaction();
        try{
            $orderService = new OrderService($bet_body,$device_name,$device_uuid);
            $response = $orderService->process_bet();

            if($response){
                DB::commit();
                return $response;
            }
        }catch(Exception $ex){
            DB::rollback();
            return responseError($ex->getMessage());
        }
    }
}

app/Http/Controllers/Sethei5D/Order/OrderController.php
<?php

namespace App\Http\Controllers\Sethei5D\Order;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Sethei5D\OrderTemp;
use App\Model\Sethei5D\Order;
use App\Model\Sethei5D\Cycle;
use App\User;
use DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use App\Http\Controllers\Sethei5D\Order\OrderTempController;

class OrderController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-5d-history-report')->only(['ajaxGetOrderDetail','showSelectionForm','index']);
        $this->middleware('permission:export-5d-history-report')->only(['downloadExcel','downloadSumBet']);
    }

    public function index(Request $request)
    {
        ini_set('max_execution_time', 0);
        ini_set('memory_limit', '-1');
        
        $data = [];
        $cycle = request()->cycle_id ? Cycle::findOrFail(request()->cycle_id) : null;
        $orderTempController = OrderTempController::withTable(Order::getModel()->getTable());

        $data = request()->user_id ? $orderTempController->getOrderDataByUser() : $orderTempController->getOrderDataSummary();
        
        return view('sethei-5d.order.report.index',compact('data','cycle'));
    }

    public function downloadExcel($requests = null){
        ini_set('max_execution_time', 0);
        ini_set('memory_limit', '-1');
        
        $orderTempController = new OrderTempController;
        $table = Order::getModel()->getTable(); 
        
        $request = $requests ?: request();
        if($request->account){
            $user = User::where('account_number',$request->account)->first();
            $request->request->add([
                'level' => $user->level,
                'parent_id' => $user->id
            ]);
            
        }
        
        $data = $orderTempController->structureTicketDataForEachUser($table,$request);
        $path = $orderTempController->writeExcel($data,true);
        
        if($requests){
            return $path;
        }else{
            return response()->json(['path' => $path, 'success' => true]);
        }

    }

    public function showSelectionForm(){
        $cycles = Cycle::orderBy('cycle_sn','DESC')->whereStateAndHasReleased(0,1)->pluck('cycle_sn','id')->toArray();
        $cycles = ['0' => 'Choose'] + $cycles;
        return view('sethei-5d.order.report.selection-form',compact('cycles'));
    }

    public function ajaxGetOrderDetail($ticket){
        $success = false;
        $data = [];
        $orders = Order::with('user')->whereTicket($ticket)->get();
        if($orders && $orders->count() > 0){
            $data = [
                'ticket' => $orders[0]->ticket,
                'betAmount' => currencyFormat($orders->sum('amount')),
                'winAmount' => currencyFormat($orders->sum('win_amount')),
                'created_at'=> date('Y-m-d H:i A', strtotime($orders[0]->created_at)),
            ];

            // if($orders[0]->user->level != 0){
            //     for($i=1 ; $i < $orders[0]->user->level + 1 ; $i++){ 
            //         $data['rebates'][] = [
            //             'levelTitle' => getUserLevelTitle($i),
            //             'username' => $orders[0]->parent($i)->username,
            //             'rebate' => currencyFormat($orders->sum('l'.$i.'_rebate'))
            //         ];
            //     }
            // }else{
            //     $data['rebates'][] = [
            //         'levelTitle' => getAdminLanguageData()['LANG_MENU_DIRECT_USER'],
            //         'username' => $orders[0]->user->username,
            //         'rebate' => currencyFormat(0)
            //     ];
            // }
            $success = true;
        }
        return response()->json(['success' => $success, 'data' => $data]);
    }

    public function writeBetWorksheet($spreadsheet, $sheet, $data){
    
        $columnNames = [
                'UserName',
                'AccountNo',
                'Province',
                'District',
                'Address',
                'Create At',
                'Sale Supervisor',
                'Sale Area Manager',
                'Sale Director',
                'Bet Amount',
                'Win Amount',
                'Type',
                'Phone'
            
        ];
        
        $sheet = $this->writeBetHeaderWorksheet($sheet, $columnNames);
        $i = 2;
        foreach($data as $value){
            $sheet->setCellValue('A'.$i,$value['username']);
            $sheet->setCellValue('B'.$i,$value['accountno']);
            $sheet->setCellValue('C'.$i,$value['province']);
            $sheet->setCellValue('D'.$i,$value['district']);
            $sheet->setCellValue('E'.$i,$value['address']);
            $sheet->setCellValue('F'.$i,$value['created_at']);
            $sheet->setCellValue('G'.$i,$value['saleSupervisor']);
            $sheet->setCellValue('H'.$i,$value['saleAreaManager']);
            $sheet->setCellValue('I'.$i,$value['saleDirector']);
            $sheet->setCellValue('J'.$i,$value['betAmount']);
            $sheet->setCellValue('K'.$i,$value['winAmount']);
            $sheet->setCellValue('L'.$i,$value['type']);
            $sheet->setCellValue('M'.$i,$value['phone']);
            $i++;
        }

        return $spreadsheet;
    }

    public function writeBetHeaderWorksheet($sheet, $columnNames){
        $columns = [];
        $a = 'A';
        foreach($columnNames as $index => $value){
            array_push($columns, $a++);
        }

        for($iterator=0;$iterator<count($columns);$iterator++){
            $sheet->setCellValue($columns[$iterator].'1', $columnNames[$iterator]);
            $sheet->getStyle($columns[$iterator].'1')
                ->getFill()
                ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
                ->getStartColor()
                ->setARGB('888888');

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->getColor()
                ->setARGB(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE);

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->setSize(11);

            $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->setBold(true);

                $sheet->getStyle($columns[$iterator].'1')
                ->getFont()
                ->setBold(true);
            $sheet->getColumnDimension($columns[$iterator])->setAutoSize(true);
        }

        return $sheet;
    }

}

resources/views/sethei-5d/order/temp/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">{{ $settings['language']['LANG_MENU_THIS_ORDER'] }}</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
        <div class="header-elements d-none">
            @canany(['export-5d-order-list'])
            {{-- <div class="d-flex justify-content-center">
                <button class="btn btn-link btn-primary btn-sm text-white" id="downloadExcelButton" 
                data-route="{{route('5d.orders.temp.download')}}" 
                data-toggle="modal" data-target="#downlod_modal">
                    <i class="icon-file-excel text-white mr-1"></i> {{ $settings['language']['LANG_LABEL_DOWN'] }}
                </button>
            </div> --}}
            @endcanany
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Sethei 5D</span>
                <span class="breadcrumb-item active">{{ $settings['language']['LANG_MENU_THIS_ORDER'] }}</span>
                <span class="breadcrumb-item active">Current</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->
<div class="content">

    @if(request()->has('user_id'))
        <div class="breadcrumb">
            <a href="{{route('5d.orders.temp.index')}}" class="breadcrumb-item pt-0">{{ $settings['language']['LANG_LABEL_ALL'] }}</a>
            <span class="breadcrumb-item active pt-0">{{ $data['data'][0]['username'] }} – {{ $data['data'][0]['account_number'] }}</span>
        </div>
    @else 
        {{ Form::open(['route' => '5d.orders.temp.index', 'method' => 'GET', 'class' => 'form-inline d-block d-sm-flex']) }}
            <div class="form-group mb-2 mr-2">
                <div class="input-group input-group-sm">
                    {{Form::text("keyword",request()->keyword,["class" => "form-control", "placeholder" => 'keyword','id' => 'keyword'])}}
                </div>
            </div>
            <div class="form-group mb-2 mr-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <div class="input-group-text">{{ $settings['language']['LANG_LABEL_START_DT'] }}</div>
                    </div>
                    <input type="text" class="form-control datetimepicker" value="{{isset($_GET['begin_date']) ? $_GET['begin_date'] : date('Y-m-d 16:45:00',strtotime('-1 days'))}}" name="begin_date">
                </div>
            </div>
            <div class="form-group mb-2 mr-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <div class="input-group-text">{{ $settings['language']['LANG_LABEL_END_DT'] }}</div>
                    </div>
                    <input type="text" class="form-control datetimepicker" value="{{isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-d 16:45:00')}}" name="end_date">
                </div>
            </div>
            {{Form::submit('Query',['class' => 'btn btn-sm btn-primary mb-2 mr-2'])}}
            <a href="{{route('5d.orders.temp.index')}}" class="btn btn-warning btn-sm mb-2">Reset</a>
        {{ Form::close() }}

        @if(isset($data['total']))
            <div class="card">
                <div class="card-header p-2 font-weight-bold text-success">Grand Total</div>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="bg-slate-800 font-weight-bold">
                                <th class="font-weight-bold">Grand Total Users</th>
                                <th class="font-weight-bold">Grand Total Tickets</th>
                                <th class="font-weight-bold">Grand Total Order</th>
                                <th class="font-weight-bold" colspan="2">Grand Total Amount</th>
                                <th class="font-weight-bold" colspan="2">Grand Total Rebate</th> 	 		
                            </tr>
                        </thead>
                        
                        <tbody>
                            <tr>
                                <td class="font-weight-bold"> {{ $data['total']['grandTotalUser'] }}</td>
                                <td class="font-weight-bold"> {{ $data['total']['grandTotalTicket'] }}</td>
                                <td class="font-weight-bold">{{ $data['total']['grandTotalOrder'] }}</td>
                                <td class="font-weight-bold">(R) {{ currencyFormat($data['total']['grandTotalAmountR']) }}</td>
                                <td class="font-weight-bold">($) {{ currencyFormat($data['total']['grandTotalAmountD']) }}</td>
                                <td class="font-weight-bold">(R) {{ currencyFormat($data['total']['grandTotalRebateR']) }}</td>
                                <td class="font-weight-bold">($) {{ currencyFormat($data['total']['grandTotalRebateD']) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    @endif

    <div class="card">
        @if(!request()->has('user_id'))
            <div class="card-header p-2 font-weight-bold text-primary">Total by user</div>
        @endif
        <div class="table-responsive">
            <table class="table table-bordered">
                @if(!request()->has('user_id'))
                    <thead>
                        <tr class="bg-slate-800">
                            <th>{{ $settings['language']['LANG_LABEL_ACCOUNT_NO'] }}</th>
                            <th>{{ $settings['language']['LANG_LABEL_USERNAME'] }}</th>
                            <th>Total Tickets</th>
                            <th>Total Order</th>
                            <th colspan="2">Total Amount</th>
                            <th colspan="2">Total Rebate</th> 	 		
                        </tr>
                    </thead>
                    
                    <tbody>
                        @if(isset($data['data']) && count($data['data']) > 0)
                            @foreach($data['data'] as $row)
                                <tr>
                                    <td>
                                        <a href="{{route('5d.orders.temp.index').'?user_id='.$row['user']['id']}}">{{ $row['user']['account_number'] }}</a>
                                    </td>
                                    <td>
                                        <a href="{{route('5d.orders.temp.index').'?user_id='.$row['user']['id']}}">{{ $row['user']['username'] }}</a>
                                    </td>
                                    <td> {{ $row['totalTicket'] }}</td>
                                    <td>{{ $row['totalOrder'] }}</td>
                                    <td>(R) {{ currencyFormat($row['totalAmountR']) }}</td>
                                    <td>($) {{ currencyFormat($row['totalAmountD']) }}</td>
                                    <td>(R) {{ currencyFormat($row['totalRebateR']) }}</td>
                                    <td>($) {{ currencyFormat($row['totalRebateD']) }}</td>
                                </tr>
                            @endforeach

                        @else 
                            <tr><td colspan="8">No Data</td></tr>
                        @endif
                    </tbody>
                @else 
                    <thead>
                        <tr class="bg-slate-800">
                            <th>{{ $settings['language']['LANG_LABEL_TICKET'] }}</th>
                            <th>{{ $settings['language']['LANG_LABEL_POST_TIME'] }}</th>
                            <th>{{ $settings['language']['LANG_LABEL_PRIZE'] }}</th>
                            <th>{{ $settings['language']['LANG_LABEL_BET'] }}</th>
                            <th>PC/U</th>
                            <th colspan="2">{{ $settings['language']['LANG_LABEL_AMOUNT'] }}</th>
                            <th colspan="2">{{ $settings['language']['LANG_LABEL_TICKET_SUM'] }}</th> 	 		
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($data['data'][0]['tickets'] as $t => $ticket)
                            @foreach($ticket['orders'] as $index => $row)
                                @if($index == 0)
                                    <tr style="background-color:#eaf9eb">
                                        <td style="vertical-align: top; cursor:pointer" class="show-order-detail" data-toggle="modal" data-target="#order_detail_modal" 
                                            data-route="{{route('5d.orders.temp.get-order-detail',$ticket['ticket'])}}">{{ $ticket['ticket'] }}</td>
                                        <td style="vertical-align: top;">{{ $ticket['created_at'] }}</td>
                                        <td>{{ $row['prize'] }}</td>
                                        <td>{{ $row['bet'] }}</td>
                                        <td>{{ currencyFormat($row['unit']) }}</td>
                                        <td>(R) {{ currencyFormat($row['amountR']) }}</td>
                                        <td>($) {{ currencyFormat($row['amountD']) }}</td>
                                        <td style="vertical-align: top;">(R) {{ currencyFormat($ticket['ticketAmountR']) }}</td>
                                        <td style="vertical-align: top;">($) {{ currencyFormat($ticket['ticketAmountD'])  }}</td>
                                    </tr>
                                @else 
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>{{ $row['prize'] }}</td>
                                        <td>{{ $row['bet'] }}</td>
                                        <td>{{ currencyFormat($row['unit']) }}</td>
                                        <td>(R) {{ currencyFormat($row['amountR']) }}</td>
                                        <td>($) {{ currencyFormat($row['amountD']) }}</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                @endif
                            @endforeach
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th></th><th></th><th></th><th></th><th></th>
                            <th colspan="2">Grand Total</th>
                            <th>(R) {{ currencyFormat($data['total']['totalAmountR']) }}</th>
                            <th>($) {{ currencyFormat($data['total']['totalAmountD']) }}</th>
                        </tr>
                    </tfoot>
                @endif
            </table>
        </div>
    </div>
</div>
<div id="downlod_modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-teal-400">
                <h5 class="modal-title">{{$settings['language']['LANG_LABEL_DOWN']}}</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body text-center p-4 h5 m-0" id="downloadModalBody">
                <i class='icon-spinner2 spinner'></i> Downloading...
            </div>
        </div>
    </div>
</div>
<div id="order_detail_modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-teal-400">
                <h5 class="modal-title">Order Detail</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" id="body">
                
            </div>
        </div>
    </div>
    
</div>
@endsection

@section('page-script')
<script src="/global_assets/js/plugins/ui/moment/moment.min.js"></script>
<script src="/global_assets/js/plugins/pickers/daterangepicker.js"></script>
@endsection